### ISSUE TITLE
parameter in config.yml

### ISSUE THREAD

**Issue by huangssssir** [nicholasbalasus/blended_tropomi_gosat_methane#1]
I found "a" and "b" set in the config.yml and used in prediction, what are they mean?
The prediction made by machine learning is the difference between gosat and tropomi that  adjust the profile and pressure level， but the raw tropomi data is not corrected by the prior profile. I am a little confused with it.
Thank you !

**Comment by nicholasbalasus** [comment]
Hi @huangssssir - `a` and `b` are used to perform a linear Z-score transform on the model predictions. They are derived based on the training data. This is mentioned in Line 170-171 of the [manuscript](https://amt.copernicus.org/preprints/amt-2023-47/amt-2023-47.pdf).

**Comment by huangssssir** [comment]
Thank you, I get it ! But I still have a question that, the ML model predicts the difference that corrected by the gosat prior profile, but the "xch4_corrected"variable doesn't correct this. Can these two values be directly subtracted?

**Comment by nicholasbalasus** [comment]
We calculate ∆(TROPOMI-GOSAT) accounting for differences in the prior and vertical sensitivity of the instrument because we know these differences will exist (and may not be predictable). The remaining differences (due to scattering properties of the atmosphere, surface properties, etc.) are those that we are interested in w.r.t. any bias they may cause.

We wouldn't be able to correct all of the raw TROPOMI data (~450 million) to the GOSAT prior and averaging kernel since this information is only available to use when we have TROPOMI/GOSAT pairs (~150,000).

Regardless, accounting for the prior profiles and averaging kernels has a small effect on ∆(TROPOMI-GOSAT) (see plot below). Let me know if this clears it up or if you have further questions!

![image](https://user-images.githubusercontent.com/91984611/235164405-d4c34309-5aac-40b6-b0f3-4811955a312e.png)

**Comment by huangssssir** [comment]
I understand！ Thank you very much and have a nice day~
